import type { Metadata } from "next";
import "@/app/globals.css";
import { Header } from "@/components/shared/header";

export const metadata: Metadata = {
  title: "Pizza | Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      <Header />
      {children}
    </main>
  );
}
