import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/shared/header";

export const metadata: Metadata = {
  title: "Pizza",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
