import type { Metadata } from "next";
import "@/app/globals.css";

export const metadata: Metadata = {
  title: "Pizza | Authentication",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="h-screen w-screen flex justify-center pt-20 box-border">
      {children}
    </main>
  );
}
